- name: enabling RAPI to listen on 0.0.0.0
  lineinfile:
    path: /etc/default/ganeti
    regexp: ^RAPI_ARGS=
    line: RAPI_ARGS="--require-authentication"
  register: rapi_listen

- name: restart ganeti
  service:
    name: ganeti
    state: restarted
  when: rapi_listen is changed

- name: configuring RAPI user
  copy:
    dest: /var/lib/ganeti/rapi/users
    content: ganeti-qa {cleartext}foo555 write
  notify: restart ganeti

- name: distributing RAPI config and user
  command: gnt-cluster copyfile {{ item }}
  with_items:
    - /etc/default/ganeti
    - /var/lib/ganeti/rapi/users

- name: installing QA toolings
  apt:
    name:
      - iptables

- name: prefill ssh know_hosts
  shell: ssh-keyscan -f /var/lib/ganeti/ssconf_node_list -f /var/lib/ganeti/ssconf_node_primary_ips -f /var/lib/ganeti/ssconf_node_secondary_ips > /root/.ssh/known_hosts

- name: templating qa-config
  template:
    src: qa-config.json
    dest: /tmp/qa-config.json

- name: running qa
  command: /tmp/running/qa/ganeti-qa.py --yes-do-it /tmp/qa-config.json
  environment:
    PYTHONPATH: /tmp/running
